# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageClassifier' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageClassifier
pod 'YPImagePicker'
pod 'Hero'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Storage'
pod 'CardSlider'

end
